### ISSUE TITLE
Option to treat device as key-value pair

### ISSUE THREAD

**Issue by Tank-Missile** [b10011/pyfstab#2]
Devices can be UUID=XXXXX, LABEL=XXXXX, and PARTUUID=XXXXX.

**Comment by b10011** [comment]
@Tank-Missile can you describe the ways this feature could be helpful? Some rough code examples of the usage would be great.

**Comment by Tank-Missile** [comment]
@b10011 Being able to access the label itself would be useful for displaying the labels on a menu, or using them in other commands. What type a device is (label, uuid, or partuid) can be determined by the key. Obviously, if it's a regular /dev/ device, there is no key. In that case, the key could stay empty and the value could be the device. A tuple would also suffice. Below is an example of how it might be used. While we're on the subject of examples, I just want to mention how much I like using the pathlib library. Direct support for just putting in a file without having to open it first would be nice.

```python
from pathlib import Path
from pyfstab import Fstab

fstab_file = Path('/etc/fstab')
fstab = Fstab().read_string(fstab_file.read_text())

for entry in fstab.entries:
    print(entry.device[0]) # Prints UUID, LABEL, or PARTUUID
    print(entry.device[1]) # Prints actual uuid, label, partuuid, or /dev/sda1
    # Another way:
    print(entry.device.key)
    print(entry.device.value)
```

**Comment by b10011** [comment]
@Tank-Missile Thanks, looks reasonable, even though it's a bit trivial to check in the code!

I think I shouldn't change how `entry.device` is formatted due to backwards-compatibility. However, I could add `entry.device_tag_type` and `entry.device_tag_value`. `device_tag` is a reference to `mount(8)` documentation, which mentions the term "tag" ([Manpage](https://man7.org/linux/man-pages/man8/mount.8.html)). If the `device` is a file path or block device, it could be retrieved through `entry.device_tag_value` with `entry.device_tag_type` being `None`.

You mentioned that the reading should happen in the constructor. As far as I have seen, people often tend to move stuff that could cause errors out of the `__init__` method so that you can trust that you can always initialize the object. See the example below:

```python
from pyfstab import Fstab

fstab = Fstab()
try:
    fstab.read_file("/etc/fstab")
except (FileNotFoundError, PermissionError, OSError):
    logger.warning("Couldn't read /etc/fstab, creating new")

# You can continue to use the `fstab` object because it's initialized properly even though nothing was loaded
```

**Comment by b10011** [comment]
@Tank-Missile I added support for `entry.device_tag_type` and `entry.device_tag_value`. Check out the README.rst for examples.

**Comment by Tank-Missile** [comment]
@b10011 Perfect! Thanks for the quick update. While the fstab file has a relatively simple format, having a library handle splitting text into accessible chunks is always useful. If you don't mind, I would like to make an AUR package for this.

**Comment by b10011** [comment]
@Tank-Missile Sounds good! I use Arch and Manjaro myself too. Would it be possible for you to add me to the maintainers of that AUR package so that I could push new versions whenever I update the library to PyPI?
